name: Test bars, secrets

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  # Setting an environment variable with the value of a configuration variable
  REGISTRY_ORG_VAR: ${{ vars.QUAY_ORG }}
  REGISTRY_ORG_SECRET: ${{ secrets.QUAY_ORG }}

jobs:
  display-variables:
    name: show-variables-secrets
    runs-on: ubuntu-latest
    steps:
      - name: Use variables
        run: |
          echo "Registry org variable: $REGISTRY_ORG_VAR"
          echo "Registry org secret: $REGISTRY_ORG_SECRET"
          
          echo "Env var set from workflow env var: $VAR1"
          echo "Env var set from workflow env secret: $SECRET1"
        env:
          VAR1: $REGISTRY_ORG_VAR
          SECRET1: $REGISTRY_ORG_SECRET
