name: test shared matrix
on:
  push:
    branches:
      - main

jobs:
  builder:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          json_include=$(cat <<EOF | yq -P -o=json -
          include:
            builder-image: [ 'paketobuildpacks/builder-jammy-tiny:0.0.175' ]
            pack_cli_version: [ 'v0.30.0-rc1' ]
          EOF
          )
          json_include_oneline=$(echo $json_include | jq -c . -)
          echo "matrix=$json_include_oneline" >> $GITHUB_OUTPUT

  process:
    needs: builder
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.builder.outputs.matrix) }}
    steps:
      - run: |
          echo "Builder image: ${{ matrix.builder-image }}"
          echo "Pack client image: ${{ matrix.pack_cli_version }}"