name: Test shared matrix

on:
  push:
    branch: test

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v3
      - id: set-matrix
        run: |
          # Syntax is working
          # echo 'matrix={"include":[{"builder-image":"paketobuildpacks/builder-jammy-tiny:0.0.175","pack_cli_version":"v0.30.0-rc1"}]}' >> $GITHUB_OUTPUT
          
          # This syntax dot not work and job reports: A mapping was not expected
          #echo 'matrix={"builder-image":"paketobuildpacks/builder-jammy-tiny:0.0.175","pack_cli_version":"v0.30.0-rc1"}' >> $GITHUB_OUTPUT
          
          # This syntax works -> see comment withing config.yaml
          echo "matrix=$(yq -P -o=json config.yaml | jq -c .)" >> $GITHUB_OUTPUT

  job1:
    needs: configure
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.configure.outputs.matrix) }}
    steps:
      - run: |
          echo "Builder image: ${{ matrix.builder-image }}"
          echo "Pack client image: ${{ matrix.pack_cli_version }}"