name: Test shared matrix

on: [push]

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v3
      - name: yaml-to-json
        run: |
          yq -P -o=json matrix1.yaml > matrix1.json
      - id: set-matrix
        run: |
          # Syntax is working
          # echo 'matrix={"include":[{"project":"foo","config":"Debug"},{"project":"bar","config":"Release"}]}' >> $GITHUB_OUTPUT
          
          # This syntax reports a : A mapping was not expected
          #echo 'params={"builder-image":"paketobuildpacks/builder-jammy-tiny:0.0.175","pack_cli_version":"v0.30.0-rc1"}' >> $GITHUB_OUTPUT
          
          # This syntax works
          echo "matrix=$(jq -c . < ./matrix1.json)" >> $GITHUB_OUTPUT

  job1:
    needs: configure
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.configure.outputs.matrix) }}
    steps:
      - run: |
          echo "Builder image: ${{ matrix.builder-image }}"
          echo "Pack client image: ${{ matrix.pack_cli_version }}"