name: test shared matrix
on:
  push:
    branches:
      - main

jobs:
  builder:
    name: set matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cfg:
          - data:
            - { builder-image: paketobuildpacks/builder-jammy-tiny:0.0.175 }
            - { builder-image: paketobuildpacks/builder-jammy-tiny:0.0.173 }
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        env:
          CFG: ${{ toJSON(matrix.cfg) }}
        run: |
          # jq -r -n  'env.CFG | fromjson | @json "result=\(.data)"'
          echo "name=[{"builder-image":"paketobuildpacks/builder-jammy-tiny:0.0.175"},{"builder-image":"paketobuildpacks/builder-jammy-tiny:0.0.173"}]" >> $GITHUB_OUTPUT

  runner:
    needs: [ builder ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cfg: ${{ fromJson(needs.builder.outputs.matrix) }}
    steps:
      - run: |
          echo  "Builder-image: ${{ matrix.cfg.builder-image }}"