name: test shared matrix
on:
  push:
    branches:
      - main

jobs:
  builder:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          wget -q https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O yq
          chmod +x yq; sudo mv yq /usr/local/bin.yq
          cat <<EOF > matrix.yml
          matrix:
            include:
              builder-image: [ 'paketobuildpacks/builder-jammy-tiny:0.0.175' ]
              pack_cli_version: [ 'v0.30.0-rc1' ]
          EOF
          ls -la
          yq -v -o=json matrix.yml #>> $GITHUB_OUTPUT
  process:
    needs: builder
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.builder.outputs.matrix) }}
    steps:
      - run: |
          echo "Builder image: ${{ matrix.builder-image }}"
          echo "Pack client image: ${{ matrix.pack_cli_version }}"