name: Shared matrix - same workflow

on:
  workflow_dispatch:

jobs:
  jobProd:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          echo "matrix={\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}" >> $GITHUB_OUTPUT

  jobCons:
    needs: jobProd
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.jobProd.outputs.matrix) }}
    steps:
      - run: |
          echo "Matrix: ${{ matrix.project }}"
          cfg=$(echo ${{ fromJSON(needs.jobProd.outputs.matrix) }})
          echo "Cfg: " $cfg