name: Reusable workflow

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      firstword:
        description: "The first output string"
        value: ${{ jobs.reuse.outputs.output1 }}
      secondword:
        description: "The second output string"
        value: ${{ jobs.reuse.outputs.output2 }}
      matrix:
        description: "Matrix of configurations"
        value: ${{ jobs.reuse.outputs.matrix }}

jobs:
  reuse:
    name: Generate output
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      output1: ${{ steps.step1.outputs.firstword }}
      output2: ${{ steps.step2.outputs.secondword }}
      output3: ${{ steps.step3.outputs.matrix }}
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v3

      - id: step1
        run: echo "firstword=hello" >> $GITHUB_OUTPUT

      - id: step2
        run: echo "secondword=world" >> $GITHUB_OUTPUT

      - id: step3
        name: Convert config from YAML to JSON and pass it as value to matrix
        run: |
          matrix="matrix=$(yq -P -o=json config.yaml | jq -c .)"
          echo $matrix
          echo $matrix >> $GITHUB_OUTPUT
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          echo "matrix={\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}" >> $GITHUB_OUTPUT
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.job1.outputs.matrix) }}
    steps:
      - run: |
          echo "Matrix: ${{ matrix.project }}"
