name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:

jobs:
  job1:
    uses: ./.github/workflows/wf_a.yml

  job2:
    runs-on: ubuntu-latest
    needs: job1
    #strategy:
    #  matrix: ${{ fromJSON(needs.job1.outputs.matrix) }}
    steps:
      - name: Log HelloWorld Message & JSON matrix ...
        run: |
          echo "Matrix: ${{ needs.job1.outputs.matrix }}"
          echo 'Matrix: ${{ needs.job1.outputs.matrix }}'
          echo "${{ needs.job1.outputs.matrix }}" | jq -r .include
          echo "${{ needs.job1.outputs.matrix }}" | jq -r .
          
          echo "Message: ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}"
