name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:

jobs:
  job1:
    uses: ./.github/workflows/wf_a.yml

  job2:
    runs-on: ubuntu-latest
    needs: job1
    #strategy:
    #  matrix: ${{ fromJSON(needs.job1.outputs.matrix) }}
    steps:
      - run: |
          echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
          
          echo "Matrix: ${{ needs.job1.outputs.matrix) }}"
          
          #echo "Builder image: ${{ matrix.builder-image }}"
          #echo "Pack client image: ${{ matrix.pack_cli_version }}"
