name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:

jobs:
  job1:
    uses: ./.github/workflows/wf_a.yml

  job2:
    runs-on: ubuntu-latest
    needs: job1
    #strategy:
    #  matrix: ${{ fromJSON(needs.job1.outputs.matrix) }}
    steps:
      - name: Log Hello World message
        run: |
          echo "Message: ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}"

      - name: Log JSON matrix
        run: |
          echo "Matrix: ${{ fromJSON(needs.job1.outputs.matrix ) }}
          #echo "Project: ${{ needs.job1.outputs.project }}"
          
          #echo "Builder image: ${{ matrix.builder-image }}"
          #echo "Pack client image: ${{ matrix.pack_cli_version }}"
